print("___________________________________")
print("Task9")
print("___________________________________")
print("Input text block")
txt1=input()
print("You have entered:", txt1)
Txt_List = txt1.split(" ")
Txt_List[1]=Txt_List[1].upper()
str=" ".join(Txt_List)
print("Result of this task is:" ,Txt_List)