print("___________________________________")
print("Task9")
print("___________________________________")
print("Input text block")
txt1=input()
print("You have entered:", txt1)
txt_list = txt1.split(" ")
txt_list[1]=txt_list[1].upper()
str=" ".join(txt_list)
print("Result of this task is:" ,txt_list)